### ISSUE TITLE
Workaround for error Invalid repository ppa:webupd8team/java 

### ISSUE THREAD

**Issue by nodermatt** [malk/ansible-java8-oracle#8]
Note that I had to add the repository differently because "apt_repository: repo='ppa:webupd8team/java' state=present" threw an error saying that it was an invalid repository. I got the id from the webupd8team/java website

```
- name: Add an apt key by id from a keyserver
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7B2C3B0889BF5709A105D03AC2518248EEA14886
    state: present
    
- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present
```

The license acceptance and java installation part was working fine
